# Project information
site_name: VirtualHub
site_url: https://virtualhub.eu.org
site_author: Legacy Installer
site_description: >-
  Install old Operating Systems in Virtual Machines and enjoy what you missed
  without worrying about buying old computers and peripherals

# Repository
repo_name: virtualhub.eu.org
repo_url: https://github.com/InstallerLegacy/virtualhub.eu.org

# Copyright
copyright: Copyright &copy; 2021 - 2023 <a href="https://twitter.com/Virtua1Hub">Legacy Installer</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.link
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/monitor
    repo: fontawesome/brands/github
  favicon: assets/favicon.svg

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - glightbox

# Customization
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/InstallerLegacy
      name: VirtualHub on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Virtua1Hub
      name: VirtualHub on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@virtua1hub
      name: VirtualHub on Youtube
    - icon: material/email
      link: mailto:contact@virtualhub.eu.org
      name: VirtualHub e-mail
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/virtua1hub
      name: VirtualHub on Telegram

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
    - Home: index.md
    - About:
      - about/index.md
      - websites.md
      - contact.md
    - 1980s:
      - 1980s/index.md
      - 1981:
        - 1980s/1981/index.md
        - DOS:
          - 1980s/1981/DOS/index.md
          - 86-DOS:
            - 1980s/1981/DOS/86-DOS/index.md
            - 86-DOS 1.00:
              - 1980s/1981/DOS/86-DOS/1.00/index.md
              - 1980s/1981/DOS/86-DOS/1.00/altairz80.md
              - 1980s/1981/DOS/86-DOS/1.00/virtualbox.md
              - 1980s/1981/DOS/86-DOS/1.00/86box.md
              - 1980s/1981/DOS/86-DOS/1.00/pcem.md
              - 1980s/1981/DOS/86-DOS/1.00/dosbox-staging.md
              - 1980s/1981/DOS/86-DOS/1.00/dosbox-x.md
              - 1980s/1981/DOS/86-DOS/1.00/mame.md
              - 1980s/1981/DOS/86-DOS/1.00/pce.md
            - 86-DOS 1.14:
              - 1980s/1981/DOS/86-DOS/1.14/index.md
              - 1980s/1981/DOS/86-DOS/1.14/altairz80.md
          - PC-DOS:
            - 1980s/1981/DOS/PC-DOS/index.md
            - PC-DOS 1.10:
              - 1980s/1981/DOS/PC-DOS/1.10/index.md
              - 1980s/1981/DOS/PC-DOS/1.10/virtualbox.md
              - 1980s/1981/DOS/PC-DOS/1.10/vmware-workstation.md
              - 1980s/1981/DOS/PC-DOS/1.10/vmware-player.md
              - 1980s/1981/DOS/PC-DOS/1.10/qemu.md
              - 1980s/1981/DOS/PC-DOS/1.10/virt-manager.md
              - 1980s/1981/DOS/PC-DOS/1.10/dosbox.md
              - 1980s/1981/DOS/PC-DOS/1.10/dosbox-staging.md
              - 1980s/1981/DOS/PC-DOS/1.10/dosbox-x.md
              - 1980s/1981/DOS/PC-DOS/1.10/86box.md
              - 1980s/1981/DOS/PC-DOS/1.10/pcem.md
              - 1980s/1981/DOS/PC-DOS/1.10/pce.md
              - 1980s/1981/DOS/PC-DOS/1.10/bochs.md
              - 1980s/1981/DOS/PC-DOS/1.10/mame.md
          - MS-DOS:
            - 1980s/1981/DOS/MS-DOS/index.md
            - MS-DOS 1.25:
              - 1980s/1981/DOS/MS-DOS/1.25/index.md
              - 1980s/1981/DOS/MS-DOS/1.25/virtualbox.md
              - 1980s/1981/DOS/MS-DOS/1.25/qemu.md
              - 1980s/1981/DOS/MS-DOS/1.25/virt-manager.md
              - 1980s/1981/DOS/MS-DOS/1.25/dosbox.md
              - 1980s/1981/DOS/MS-DOS/1.25/dosbox-staging.md
              - 1980s/1981/DOS/MS-DOS/1.25/dosbox-x.md
              - 1980s/1981/DOS/MS-DOS/1.25/86box.md
              - 1980s/1981/DOS/MS-DOS/1.25/pcem.md
              - 1980s/1981/DOS/MS-DOS/1.25/pce.md
              - 1980s/1981/DOS/MS-DOS/1.25/bochs.md
              - 1980s/1981/DOS/MS-DOS/1.25/mame.md
              - 1980s/1981/DOS/MS-DOS/1.25/altairz80.md
        - CP/M:
          - 1980s/1981/CPM/index.md
          - CP/M 1.4:
            - 1980s/1981/CPM/1.4/index.md
            - 1980s/1981/CPM/1.4/altairz80.md
    - Tags: tags.md
