name: deploy 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: sudo apt-get install -y libcairo2-dev
      - run: pip install mkdocs-material pillow cairosvg \
              mkdocs-git-revision-date-localized-plugin \
              mkdocs-minify-plugin mkdocs-glightbox
      - run: mkdocs gh-deploy --force
